"""index slot lookup by date and time

Revision ID: 71e2c3d62429
Revises: 69ed89c0fecc
Create Date: 2026-09-18 03:50:35.265084
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '71e2c3d62429'
down_revision: Union[str, None] = '69ed89c0fecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_slot'))
        batch_op.create_index('ix_appointments_slot', ['appointment_date', 'appointment_time'], unique=False)
        batch_op.create_index('ix_appointments_doctor', ['doctor_id'], unique=False)
        batch_op.create_index('ix_appointments_specialist', ['specialist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointments_specialist')
        batch_op.drop_index('ix_appointments_doctor')
        batch_op.drop_index('ix_appointments_slot')
        batch_op.create_index(batch_op.f('ix_appointments_slot'), ['doctor_id', 'appointment_date', 'appointment_time'], unique=False)

    # ### end Alembic commands ###
