"""initial schema

Revision ID: 69ed89c0fecc
Revises: 
Create Date: 2026-09-18 03:34:41.746607
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69ed89c0fecc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('doctor_id', sa.String(length=128), nullable=False),
    sa.Column('doctor_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('normalized_specialty', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('clinic', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_doctor_id', sa.String(length=64), nullable=False),
    sa.Column('oladoc_profile_url', sa.Text(), nullable=False),
    sa.Column('oladoc_directory_url', sa.Text(), nullable=False),
    sa.Column('rating_label', sa.String(length=40), nullable=False),
    sa.Column('identity_strength', sa.String(length=32), nullable=False),
    sa.Column('booking_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index('ix_doctors_normalized_name', ['normalized_name'], unique=False)
        batch_op.create_index('ix_doctors_provider_doctor_id', ['provider_doctor_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('preferred_contact', sa.String(length=16), nullable=False),
    sa.Column('profile_picture', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("preferred_contact in ('email','whatsapp','phone','both')", name='ck_users_contact'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email_lower', ['email'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('doctor_id', sa.String(length=128), nullable=True),
    sa.Column('specialist_id', sa.String(length=64), nullable=False),
    sa.Column('specialist_name', sa.String(length=200), nullable=False),
    sa.Column('specialist_specialty', sa.String(length=120), nullable=False),
    sa.Column('provider_doctor_id', sa.String(length=64), nullable=False),
    sa.Column('provider_profile_url', sa.Text(), nullable=False),
    sa.Column('clinic_id', sa.String(length=64), nullable=False),
    sa.Column('clinic_name', sa.String(length=200), nullable=False),
    sa.Column('clinic_address', sa.Text(), nullable=False),
    sa.Column('clinic_fee', sa.String(length=64), nullable=False),
    sa.Column('appointment_date', sa.String(length=10), nullable=False),
    sa.Column('appointment_time', sa.String(length=8), nullable=False),
    sa.Column('time_label', sa.String(length=24), nullable=False),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('booking_type', sa.String(length=24), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('booking_status', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('booking_reference', sa.String(length=64), nullable=False),
    sa.Column('provider_appointment_id', sa.String(length=64), nullable=False),
    sa.Column('confirmation_reference', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('provider_name', sa.String(length=160), nullable=False),
    sa.Column('booking_session_id', sa.String(length=64), nullable=False),
    sa.Column('slot_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('email_status', sa.String(length=24), nullable=False),
    sa.Column('email_detail', sa.Text(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("booking_status in ('SELECTED','IN_PROGRESS','AWAITING_OTP','CONFIRMED','FAILED','CANCELLED')", name='ck_appointments_booking_status'),
    sa.CheckConstraint("email_status in ('PENDING','SENT','FAILED','NOT_CONFIGURED')", name='ck_appointments_email_status'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_appointments_slot', ['doctor_id', 'appointment_date', 'appointment_time'], unique=False)
        batch_op.create_index('ix_appointments_user_date', ['user_id', 'appointment_date', 'appointment_time'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conversation_key', name='uq_conversations_user_key')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_user', ['user_id'], unique=False)

    op.create_table('medical_information',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('encrypted_details', sa.Text(), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('encryption', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_information', schema=None) as batch_op:
        batch_op.create_index('ix_medical_information_user', ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_intent_id', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_payments_amount_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_user', ['user_id'], unique=False)

    op.create_table('redirect_handoffs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('specialist_id', sa.String(length=64), nullable=False),
    sa.Column('specialist_name', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('preferred_date', sa.String(length=10), nullable=False),
    sa.Column('preferred_time', sa.String(length=8), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payment_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redirect_handoffs', schema=None) as batch_op:
        batch_op.create_index('ix_redirect_handoffs_user', ['user_id'], unique=False)

    op.create_table('checklists',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('appointment_id', sa.String(length=32), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('appointment_id', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('desired_resolution', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index('ix_complaints_user', ['user_id'], unique=False)

    op.create_table('conversation_turns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('internal_assessment', sa.String(length=200), nullable=False),
    sa.Column('disease_name', sa.String(length=200), nullable=False),
    sa.Column('emergency', sa.Boolean(), nullable=False),
    sa.Column('recommendation', sa.JSON(), nullable=False),
    sa.Column('retrieved_documents', sa.JSON(), nullable=False),
    sa.Column('follow_up_questions', sa.JSON(), nullable=False),
    sa.Column('question_answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.create_index('ix_turns_conversation_position', ['conversation_id', 'position'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('appointment_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel in ('email','whatsapp','sms')", name='ck_notifications_channel'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('symptom_intakes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('record', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checklist_id', sa.String(length=32), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_id', 'item_key', name='uq_checklist_item_key')
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index('ix_checklist_items_checklist', ['checklist_id', 'position'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index('ix_checklist_items_checklist')

    op.drop_table('checklist_items')
    op.drop_table('symptom_intakes')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_created')

    op.drop_table('notifications')
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_index('ix_turns_conversation_position')

    op.drop_table('conversation_turns')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index('ix_complaints_user')

    op.drop_table('complaints')
    op.drop_table('checklists')
    with op.batch_alter_table('redirect_handoffs', schema=None) as batch_op:
        batch_op.drop_index('ix_redirect_handoffs_user')

    op.drop_table('redirect_handoffs')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_user')

    op.drop_table('payments')
    with op.batch_alter_table('medical_information', schema=None) as batch_op:
        batch_op.drop_index('ix_medical_information_user')

    op.drop_table('medical_information')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_user')

    op.drop_table('conversations')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointments_user_date')
        batch_op.drop_index('ix_appointments_slot')

    op.drop_table('appointments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email_lower')

    op.drop_table('users')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index('ix_doctors_provider_doctor_id')
        batch_op.drop_index('ix_doctors_normalized_name')

    op.drop_table('doctors')
    # ### end Alembic commands ###
